name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Update apt
    - run: sudo apt-get update
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra --fix-missing
    - name: Build pdf
      run: make kactl
    - name: Run compiles
      run: make test-compiles
    - name: Run stress tests
      run: make test
